version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
  server:
    depends_on:
      - db
    build:
      context: ./server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always
  client:
    build:
      context: ./client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    restart: always
